name: "Serama"
board: "Serama"

start:
  must_home: false

control:
    feed_hold_pin: gpio.36:low

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 4
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  shared_stepper_reset_pin: NO_PIN
  
  x:
    steps_per_mm: 53
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 10000
    max_travel_mm: 200
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: 4
      positive_direction: false
      feed_mm_per_min: 500
      seek_mm_per_min: 2000
    
    motor0:
      limit_neg_pin: gpio.1:high
      pulloff_mm: 2
      stepstick:
        disable_pin: gpio.15:low
        direction_pin: gpio.16
        step_pin: gpio.17
    motor1:
      null_motor:

  y:
    steps_per_mm: 47
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 10000
    max_travel_mm: 230
    soft_limits: true
    homing:
      cycle: 3
      mpos_mm: 5
      positive_direction: true
      feed_mm_per_min: 500
      seek_mm_per_min: 2000

    motor0:
      limit_neg_pin: gpio.2:low
      pulloff_mm: 4
      stepstick:
        disable_pin: gpio.18:low
        direction_pin: gpio.21:low
        step_pin: gpio.26
    motor1:
      null_motor:

  z:
    steps_per_mm: 22
    max_rate_mm_per_min: 10000
    acceleration_mm_per_sec2: 10000
    max_travel_mm: 16
    soft_limits: true
    homing:
      cycle: 1
      mpos_mm: 2
      positive_direction: true
      feed_mm_per_min: 500
      seek_mm_per_min: 1000

    motor0:
      limit_pos_pin: gpio.4:high
      pulloff_mm: 4
      stepstick:
        disable_pin: gpio.47:low
        direction_pin: gpio.33
        step_pin: gpio.34
    motor1:
      null_motor:

# OLED
i2c0:
   sda_pin: gpio.41
   scl_pin: gpio.40
   frequency: 400000
        
oled:
   i2c_num: 0
   i2c_address: 60
   width: 128
   height: 64
   radio_delay_ms: 1000

# Configure SD card in SPI mode
spi:
  miso_pin: gpio.8
  mosi_pin: gpio.9
  sck_pin: gpio.10

sdcard:
  cs_pin: gpio.12
  card_detect_pin: gpio.14
  frequency_hz: 8000000

# LED (0) and expansion IOs (1-4)
user_outputs:
  digital0_pin: gpio.5
  digital1_pin: gpio.43
  digital2_pin: gpio.44
  digital3_pin: gpio.42
  digital4_pin: gpio.6
